[Audio]
AudioMixerModuleName=AudioMixerXAudio2
PlatformFormat=OGG
PlatformStreamingFormat=OGG

PlatformHeadroomDB=-3

[TextureStreaming]
PoolSizeVRAMPercentage=70

[SystemSettings]
r.setres=1280x720
framepro.ScopeMinTimeMicroseconds=10
fx.NiagaraAllowRuntimeScalabilityChanges=1
QualityLevelMapping="high"
r.Occlusion.SingleRHIThreadStall=1
r.Nanite.Streaming.ReservedResources=1
D3D12.Bindless.ResourceDescriptorHeapSize=32768
D3D12.Bindless.SamplerDescriptorHeapSize=2048
r.PSOPrecache.GlobalShaders=1
r.DynamicRes.DynamicFrameTime=1
r.VRS.EnableSoftware=1
r.VRS.ContrastAdaptiveShading=1

[PlatformCrypto]
PlatformRequiresDataCrypto=True

[/Script/Engine.RendererSettings]
r.Shaders.RemoveUnusedInterpolators=1
r.Shadow.DetectVertexShaderLayerAtRuntime=1

[ConsoleVariables]
fx.AllowFastPathFunctionLibrary=1
FX.BatchAsync=1
FX.BatchAsyncBatchSize=8
fx.DeferrPSCDeactivation=1
FX.EarlyScheduleAsync=1
fx.EnableCircularAnimTrailDump=0
fx.GPUSimulationTextureSizeX=512
fx.GPUSimulationTextureSizeY=512
FX.GPUSpawnWarningThreshold=99999999
FX.MaxCPUParticlesPerEmitter=750
FX.MaxGPUParticlesSpawnedPerFrame=60000
fx.MaxNiagaraGPUParticlesSpawnPerFrame=120000
fx.Niagara.DebugDraw.Enabled=0
fx.Niagara.GpuComputeDebug.DrawDebugEnabled=0
fx.Niagara.WarnComponentRenderCount=999999
fx.NiagaraBatcher.FreeBufferEarly=0
fx.NiagaraDataBufferMinSize=1536
fx.NiagaraRuntimeCycleHistorySize=30
fx.ParticlePerfStats.Enabled=False
fx.ScalabilityManParallelThreshold=25
fx.ScalabilityMaxUpdatesPerFrame=25
fx.SkipVectorVMBackendOptimizations=0
r.Emitter.FastPoolEnable=1
r.Streaming.AmortizeCPUToGPUCopy=1
r.Streaming.DefragDynamicBounds=1
r.Streaming.LimitPoolSizeToVRAM=1
r.Streaming.MaxNumTexturesToStreamPerFrame=20
r.Streaming.MaxTempMemoryAllowed=256
r.Streaming.NumStaticComponentsProcessedPerFrame=30
r.Streaming.ParallelRenderAssetsNumWorkgroups=3
r.Streaming.StressTest.ExtraAsyncLatency=0
r.Streaming.UseNewMetrics=1
d3d12.AllowPoolAllocateIndirectArgBuffers=1
D3D12.InsertOuterOcclusionQuery=1
D3D12.MaxCommandsPerCommandList=20000
D3D12.PSO.DriverOptimizedDiskCache=1
D3D12.ResidencyManagement=1
D3D12.StablePowerState=0
d3d12.VRAMBufferPoolDefrag.MaxCopySizePerFrame=16777216
d3d12.VRAMTexturePoolDefrag.MaxCopySizePerFrame=16777216
D3D12.ZeroBufferSizeInMB=16
r.D3D.ForceDXC=1
r.D3D12.DRED=0
r.D3D12.LightweightDRED=0
r.D3D12.RayTracing.AllowSpecializedStateObjects=0
r.GTSyncType=1
r.RHICmdMaxOutstandingMemoryBeforeFlush=256
rhi.SyncAllowEarlyKick=1
RHI.SyncThreshold=999
RHI.TransientAllocator.BufferCacheSize=128
RHI.TransientAllocator.TextureCacheSize=128
TaskGraph.ForkedProcessMaxWorkerThreads=4
TaskGraph.NumForegroundWorkers=4
TaskGraph.PrintBroadcastWarnings=0
r.DFShadowAsyncCompute=1
r.Shadow.CachePreshadow=1
r.Shadow.CacheWholeSceneShadows=1
r.Shadow.CacheWPOPrimitives=1
r.Shadow.CSMCaching=0
r.Shadow.FadeExponent=0.75
r.Shadow.PreShadowResolutionFactor=0.3
r.Shadow.Preshadows=1
r.Shadow.UnbuiltPreviewInGame=0
r.Shadow.Virtual.Cache.AllocateViaLRU=1
r.Shadow.Virtual.Cache.InvalidateUseHZB=0
r.Shadow.Virtual.Cache.StaticSeparate=1
r.Shadow.Virtual.NonNanite.IncludeInCoarsePages=0
r.Shadow.Virtual.NonNanite.UseHZB=1
r.Shadow.Virtual.UseHZB=1
pakcache.CachePerPakFile=1
pakcache.MaxBlockMemory=384
pakcache.MaxRequestSizeToLowerLevellKB=3072
pakcache.MaxRequestsToLowerLevel=3
pakcache.NumUnreferencedBlocksToCache=20
pakcache.UseNewTrim=1
s.AdaptiveAddToWorld.Enabled=1
s.AsyncLoadingThreadEnabled=1
s.AsyncLoadingTimeLimit=2.5
s.IoDispatcherBufferMemoryMB=16
s.IoDispatcherBufferSizeKB=232
s.IoDispatcherCacheSizeMB=232
s.IoDispatcherDecompressionWorkerCount=3
s.MaxIncomingRequestsToStall=0
s.MaxLevelRequestsAtOnceWhileInMatch=2
s.MaxPrecacheRequestsInFlight=4
s.MaxReadyRequestsToStallMB=384
s.MinBulkDataSizeForAsyncLoading=99999999
s.PriorityAsyncLoadingExtraTime=0.0
s.PriorityLevelStreamingActorsUpdateExtraTime=0.0
s.ProcessPrestreamingRequests=1
r.Nanite.LargePageRectThreshold=256
r.Nanite.Streaming.DynamicallyGrowAllocations=1
r.Nanite.Streaming.Imposters=1
r.Nanite.Streaming.MaxPageInstallsPerFrame=96
r.Nanite.Streaming.StreamingPoolSize=624
r.gpucrash.collectionenable=0
r.gpucrash.datadepth=0
r.GPUCrashDebugging.Aftermath.Callstack=0
r.GPUCrashDebugging.Aftermath.Markers=0
r.GPUCrashDebugging.Aftermath.TrackAll=0
r.GPUCrashDebugging=0
r.GPUDefrag.MaxRelocations=5
r.InstanceCulling.OcclusionCull=1
r.Lumen.Reflections.AsyncCompute=0
r.Lumen.Reflections.RadianceCache=1
r.Lumen.Reflections.Temporal=1
r.Lumen.ScreenProbeGather.TemporalFilterProbes=1
r.LumenScene.DirectLighting.OffscreenShadowing.TraceMeshSDFs=0
r.LumenScene.FarField.MaxTraceDistance=500000
r.LumenScene.GPUDrivenUpdate=0
r.LumenScene.Lighting.AsyncCompute=1
r.LumenScene.MeshCardsPerTask=392
r.LumenScene.ParallelUpdate=0
r.LumenScene.PrimitivesPerTask=392
r.LumenScene.PropagateGlobalLightingChange=0
r.LumenScene.SurfaceCache.AtlasSize=2048
r.LumenScene.SurfaceCache.CardCapturesPerFrame=150
r.LumenScene.SurfaceCache.Feedback.MinPageHits=32.0
r.LumenScene.SurfaceCache.Feedback.UniqueElements=3072
r.LumenScene.SurfaceCache.NumFramesToKeepUnusedPages=128
r.LumenScene.SurfaceCache.RemovesPerFrame=160
foliage.MaxOcclusionQueriesPerComponent=8
foliage.MinOcclusionQueriesPerComponent=3
grass.MaxAsyncTasks=8
grass.MaxCreatePerFrame=6
grass.MinFramesToKeepGrass=60
r.DistanceFields.ParallelUpdate=1
r.ShaderCompiler.AllowDistributedCompilation=0
r.ShaderLibrary.PrintExtendedStats=0
r.ShaderPipelineCache.BackgroundBatchSize=3
r.ShaderPipelineCache.BatchSize=30
r.ShaderPipelineCache.BatchTime=4.0
r.ShaderPipelineCache.PrecompileBatchSize=30
r.ShaderPipelineCache.PreOptimizeEnabled=1
r.ShaderPipelineCache.ReportPSO=0
r.Shaders.Optimize=1
r.SupportAllShaderPermutations=0
ai.DestroyNavDataInCleanUpAndMarkPendingKill=0
LevelSequence.InvalidBindingTagWarnings=False
memory.logGenericPlatformMemoryStats=0
net.TickAllOpenChannels=0
r.CompileShadersForDevelopment=0
r.EnableDebugSpam_GetObjectPositionAndScale=0
r.NGX.LogLevel=0
TimerManager.DumpTimerLogResolveVirtualFunctions=0
TimerManager.DumpTimerLogSymbolNames=0
au.BakedAnalysisEnabled=0
au.DisableParallelSourceProcessing=0
au.voip.AlwaysPlayVoiceComponent=0
a.ForceParallelAnimUpdate=1
p.Chaos.VisualDebuggerEnable=0
p.RemoveFarBodiesFromBVH=1
Async.ParallelFor.YieldingTimeout=99
GeometryCache.OffloadUpdate=1
r.AmbientOcclusion.Compute.Smooth=1
r.AOAsyncBuildQueue=1
r.AsyncCreateLightPrimitiveInteractions=1
r.AsyncPipelineCompile=1
r.Bloom.AsyncCompute=1
r.CookOutUnusedDetailModeComponents=1
r.CustomDepth=3
r.DontLimitOnBattery=1
r.DownsampledOcclusionQueries=0
r.EarlyZPass=2
r.ForceAllCoresForShaderCompiling=1
r.ForceDebugViewModes=2
r.FreeSkeletalMeshBuffers=0
r.InstancedStaticMeshes.ForceRemoveAtSwap=1
r.LODFadeTime=0.75
r.NumBufferedOcclusionQueries=2
r.pso.evictiontime=30
r.UniformBufferPooling=1
r.VRS.Enable=0
r.Visibility.TaskSchedule=0
r.Visibility.FrustumCull.UseSphereTestFirst=True
r.VT.CsvStats=0
r.VT.ParallelFeedbackTasks=1
vm.OptimizeVMByteCode=1
wp.Runtime.HLOD.WarmupEnabled=1
wp.Runtime.HLOD.WarmupNanite=0
wp.Runtime.HLOD.WarmupVTScaleFactor=1.0
wp.Runtime.LevelStreamingContinuouslyIncrementalGCWhileLevelsPendingPurgeForWP=128
wp.Runtime.MaxLoadingStreamingCells=16
wp.Runtime.UpdateStreaming.EnableOptimization=True
wp.Runtime.UpdateStreamingStateTimeLimit=0.1
;r.OneFrameThreadLag=0

[/Script/Engine.InputSettings]
bEnableMouseSmoothing=False

[/Script/Engine.Engine]
bAllowMultiThreadedShaderCompile=True
bEnableQueryThreadStats=False
bSmoothFrameRate=False

[/Script/AkAudio.AkSettings]
bEnableMultiCoreRendering=True

